# done 
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

prev = 1
next = 2
fib = 0
sum = 0
while fib < 4000000:
    fib = prev + next
    print(fib)
    prev = next
    next = fib
    if fib % 2 == 0:
        print(f"even fibonacci: {fib}")
        sum = sum + fib
sum = sum + 2
print(f"sum of even fibonacci numbers: {sum}")
